version: '3.1'

services:
  app:
    container_name: musala-server
    restart: always
    build:
      context: .
      args:
        BUILD_ENV: staging
    ports:
      - '8082:8082'
    links:
      - mongoDB
  mongoDB:
    container_name: mongoDB
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
